### PR TITLE
Support Pythia checkpoints

### PR DESCRIPTION
**Pull request by carmocca**
```bash
python scripts/download.py --repo_id EleutherAI/pythia-70m --local_dir checkpoints/hf-pythia/pythia-70m
```
```bash
python scripts/convert_hf_checkpoint.py --output_dir checkpoints/lit-pythia/pythia-70m --ckpt_dir checkpoints/hf-pythia/pythia-70m
```
```bash
python generate.py --prompt "Hello, my name is" --checkpoint_path checkpoints/lit-pythia/pythia-70m/lit-stablelm.pth --config_path checkpoints/lit-pythia/pythia-70m/config.json --tokenizer_path checkpoints/lit-pythia/tokenizer.json --tokenizer_config_path checkpoints/lit-pythia/tokenizer_config.json
```

### CODE REVIEW

**Review by lantiga — APPROVED** [review]
Awesome!

**Comment by lantiga** [comment]
CPU test OOMs, let's pick the smallest model

**Comment by lantiga** [comment]
One request @carmocca : in a follow-up PR let's add all the configurations, and make them discoverable (through CLI commands).
Also add them to the howto and README.

**Comment by carmocca** [comment]
Sounds good. I'll address these separately

**Pull request merged**
